### ISSUE TITLE
[microsite] desktop visual tweaks - checklist

### ISSUE THREAD

**Issue by ericronne** [18F/climate-labs#44]
@shawnbot 
In lieu of a live bug hunt, here are some massaging suggestions :) ...

- [x] Header pic (see #43)
- [x] Let's enlarge the three header icons a bit (see below)
- [ ] Check out the image below to see how i had it gridded out, lmk if this is funky. Currently the entire content block is centered, eg, but i had the icons hanging off to the left.
- [x] I also have the nav left-aligned with the content text blocks
![image](https://cloud.githubusercontent.com/assets/9259185/14961945/07eaa662-1062-11e6-876d-b1e9eb684cac.png)
- [x] Also add just a touch of translucency to the blue box...
![image](https://cloud.githubusercontent.com/assets/9259185/14960881/82cec792-105c-11e6-9d63-5654d2d70b29.png)
- [ ] Instead of aligning the blue box with the rest of the page, can we position it so there's always equal space on the top, bottom, and left of it, like this?...
![image](https://cloud.githubusercontent.com/assets/9259185/14962480/9e5b136e-1064-11e6-84e8-05669d0319a4.png)
- [ ] If time permits, can the nav be sticky, a la [federal front door](https://labs.usa.gov/)? Design concept was to underline the active section, like so...
![image](https://cloud.githubusercontent.com/assets/9259185/14962151/f5b65a30-1062-11e6-8e97-638c9c6d608b.png)
- [x] Can we match this type size (from eiti) for the official-website text (looks a bit large now)?
![image](https://cloud.githubusercontent.com/assets/9259185/14962182/208c84aa-1063-11e6-88e4-8208e6cfa4fd.png)
- [x] Change the flag-background bar to #017BB3 (when viewport size forces the flag offscreen, ie ipad / mobile)
- [x] Text links which have an underscore by default (ie those in sentences) should lose it on hover, and ones not underscored by default (just the download list i think) should get the underline on hover (a la eiti)
- [ ] Let's try slightly increasing the normal text size a little...
![image](https://cloud.githubusercontent.com/assets/9259185/14962751/05ca329a-1066-11e6-9c7c-f74a0b9f021c.png)
- [x] Reduce spacing after the all-caps subheads by about 10 pixels (see below)
- [x] What we found and Downloads subheads should be bold (h2, you have them at 21 px, see below)
- [x] The h3's could perhaps be a bit larger (see below)
![image](https://cloud.githubusercontent.com/assets/9259185/14963245/55c3ac84-1068-11e6-9030-8122deaf8fab.png)
- [x] Add a little vertical space here...
![image](https://cloud.githubusercontent.com/assets/9259185/14964616/9c072030-106e-11e6-81ad-66cda3c96265.png)
- [x] Change the rectangle-button hovers to a simple, 3-pixel, black outline, like so...
![image](https://cloud.githubusercontent.com/assets/9259185/14964756/4c3c1fb4-106f-11e6-906a-341bc5ad520e.png)
- [x] On the preso button, make "Google slides" lowercase

I think that's it, thx! Looking swell, natch :)
LMK if you have any q's / thoughts!

**Comment by jeremiak** [comment]
Closing this now as its mostly done and published. Plus, we're out of time/budget :)

**Comment by shawnbot** [comment]
You're my hero, @jeremiak!
